# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c57dda2fff3fa0a5c6590d74f7dd48d09c269e775775b19f2c50476eb696a95bf729a4ac8844ed25ae6d7ffe518b8905b3c64a821093e81c4d051234e4f86b0
  twitter_api_key: SbWUZ134mBDB9oPGRNTcpWk9m
  twitter_api_secret: uaME0IuoIJgmioD01ZxgGarxzqp06AJjEazOgixr1PnsO2z8ho

test:
  secret_key_base: 174d2576e3fdf513a68c055f0a601cd84c7d22a11119fc547a97273228bb0f84d00360c1cf22506daa07cd5752380cbe09740cb363e576a865231b0d8a39fb39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: SbWUZ134mBDB9oPGRNTcpWk9m
  twitter_api_secret: uaME0IuoIJgmioD01ZxgGarxzqp06AJjEazOgixr1PnsO2z8ho
